src/characterBuilder/urls.py
from django.urls import path

from . import views

app_name = "characterBuilder"
urlpatterns = [
    # ex: /polls/
    path("", views.Index.as_view(), name="index"),
    path("character/<int:pk>/", views.CharacterDetailView.as_view(), name="character"),
    path("test/", views.CharacterTestView.as_view(), name="character-test"),
    path(
        "write-test/",
        views.CharacterTestCreateView.as_view(),
        name="character-test-create",
    ),
    path("new-character/", views.NewCharacterView.as_view(), name="new-character"),
    path("crypt/", views.CryptView.as_view(), name="crypt"),
]

src/grotto/api/urls.py
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter

from grotto.api import views

schema_view = get_schema_view(
    openapi.Info(
        title="Grotto API",
        default_version="v1",
        description="Idk",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register("rooms", views.RoomViewSet, basename="room")
router.register("characters", views.CharacterViewSet, basename="character")
router.register("items", views.ItemViewSet, basename="item")

urlpatterns = router.urls

urlpatterns += [
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(
        r"swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "docs/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),

    path("map/", include("mapBuilder.api.urls", namespace="map-api")),
    path("tableau/", views.TableauAPIView.as_view(), name="tableau"),
    path("enter/", views.EnterAPIView.as_view()),

]

src/grotto/game/urls.py
from django.urls import path

from . import views

app_name = "game"
urlpatterns = [
    path("enter/", views.EnterGrottoView.as_view(), name="enter"),
    # path("move/<slug:colorSlug>/", views.MoveView.as_view(), name="move"),
    # path("fire/<slug:colorSlug>/", views.FireArrowView.as_view(), name="fire"),
    path("become/<int:character_pk>/", views.BecomeCharacterView.as_view(), name="become"),
    # path("itemActions/use/<int:item_pk>/", views.UseItemView.as_view(), name="use"),
    # path("itemActions/take/<int:item_pk>/", views.TakeItemView.as_view(), name="take"),
    # path("itemActions/place/<int:item_pk>/", views.PlaceItemView.as_view(), name="place"),
    # path("itemActions/drop/<int:item_pk>/", views.DropItemView.as_view(), name="drop"),
    # path("itemActions/view/<int:item_pk>/", views.ViewItemView.as_view(), name="view"),
]

src/grotto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from grotto.views import RegisterView, TermsAcceptView

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("rooms/", include("mapBuilder.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", RegisterView.as_view(), name="register"),
    path("guild/", include("characterBuilder.urls")),
    path("game/", include("grotto.game.urls")),
    path("api/v1/", include("grotto.api.urls")),
    path("terms/", TermsAcceptView.as_view(), name="terms"),
    path(
        "privacy/",
        TemplateView.as_view(template_name="static_pages/privacy.html"),
        name="privacy",
    ),
    path(
        "agreement/",
        TemplateView.as_view(template_name="static_pages/agreement.html"),
        name="agreement",
    ),
    path(
        "reporting/",
        TemplateView.as_view(template_name="static_pages/reporting.html"),
        name="reporting",
    ),
]

src/grotto/api/views.py
from django.contrib import messages
from drf_yasg.utils import swagger_auto_schema
from rest_framework import generics, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from grotto.api import serializers
from grotto.game.services import (
    ItemService,
    GameService,
    PlayerCharacterService,
    GrottoGameWarning,
)
from characterBuilder.api.serializers import CharacterSerializer
from characterBuilder.models import Character, Visit
from mapBuilder.api.serializers import RoomSerializer
from mapBuilder.models import Room
from itemBuilder.api.serializers import ItemSerializer
from itemBuilder.models import Item


class TableauSerializerMixin:
    def get_tableau_serializer(self):
        return serializers.TableauSerializer(
            {
                "character": self.request.character,
                "room": self.request.character.room,
                "messages": [str(m) for m in messages.get_messages(self.request)],
            }
        )


class TableauAPIView(generics.GenericAPIView, TableauSerializerMixin):
    serializer_class = serializers.TableauSerializer

    def get(self, request, *args, **kwargs):
        serializer = self.get_tableau_serializer()
        # serializer.is_valid()
        return Response(serializer.data)


class GameActionMixin(TableauSerializerMixin):
    """
    Always use this as the first parent class for any game action view or viewset.
    It handles:
      * breaking the sour news to a player that their character is dead,
      * standardizing the response json to a game action
      * resolving actions (e.g. rolling for npc movement)
    """

    def dispatch(self, request, *args, **kwargs):
        self.dice_count = 0
        if request.character is None:
            raise GrottoGameWarning("Character does not exist")
        # is this character alive
        if request.character.dead:
            # message about death
            messages.add_message(request, messages.INFO, request.character.deathnote)
            # Shortcut whatever action was requested because the player is dead!
            return self.finalize_response(request, None, *args, **kwargs)
        try:
            response = super().dispatch(request, *args, **kwargs)
        except GrottoGameWarning as e:
            self.dice_count = 0
            messages.add_message(request, messages.INFO, f"{e}")
            response = self.finalize_response(request, None, *args, **kwargs)
        return response

    def finalize_response(self, request, response, *args, **kwargs):
        self.advance_game()
        response = Response(self.get_tableau_serializer().data)
        return super().finalize_response(request, response, *args, **kwargs)

    def advance_game(self):
        # TODO: make burnable_swap a scheduled task
        ItemService().burnable_swap()
        if self.dice_count == 0:
            return
        game = GameService()
        # roll for dirtying room
        game.roll_to_dirty_room(
            room=self.request.character.room, dice_count=self.dice_count
        )
        # roll for NPC movements
        service_return = game.roll_to_move_npcs(dice_count=self.dice_count)
        # send messages
        for message in service_return.messages:
            messages.add_message(self.request, messages.INFO, message)


class EnterAPIView(GameActionMixin, generics.GenericAPIView):
    serializer_class = serializers.NullSerializer

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    def post(self, request, *args, **kwargs):
        if request.character.room is None:
            # choose a random, but safe room to enter
            request.character.room = Room.objects.exclude(
                npcs__deadly=True).order_by("?")[0]
            request.character.save()


class RoomViewSet(GameActionMixin, viewsets.GenericViewSet):
    serializer_class = RoomSerializer
    queryset = Room.objects.all()

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def move(self, request, pk):
        service_return = PlayerCharacterService().move(
            character=request.character, id=pk)
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        self.dice_count += 1

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def fire_arrow(self, request, pk):
        service_return = PlayerCharacterService().fire_arrow(
            character=request.character, id=pk)
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        self.dice_count += 5


class CharacterViewSet(GameActionMixin, viewsets.GenericViewSet):
    serializer_class = CharacterSerializer
    queryset = Character.objects.all()

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def become(self, request, pk):
        character = None
        try:
            character = Character.objects.get(user=request.user, pk=pk)
        except Character.DoesNotExist:
            raise GrottoGameWarning("Character doesn't exist")
        request.user.character = character
        request.user.save()
        request.character = character


class ItemViewSet(GameActionMixin, viewsets.GenericViewSet):
    serializer_class = ItemSerializer
    queryset = Item.objects.all()

    def generic_action(self, request, pk, action="test", holder="character"):
        item_service = ItemService()
        item = item_service.get_item(
            character=request.character, pk=pk, holder=holder)
        service_return = getattr(item_service, self.action)(
            item=item, character=request.character
        )
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        return Response("this should get overwritten!")

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def use(self, request, pk):
        return self.generic_action(request, pk, action="use")

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def place(self, request, pk):
        return self.generic_action(request, pk, action="place")

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def take(self, request, pk):
        return self.generic_action(request, pk, action="take", holder="room")

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def drop(self, request, pk):
        return self.generic_action(request, pk, action="drop")

src/grotto/game/views.py
from random import choice, randint

from django.contrib import messages
from django.http import Http404
from django.views.generic import FormView, RedirectView, TemplateView

from characterBuilder.models import Character, NonPlayerCharacter, Visit
from grotto.game.services import (
    NonPlayerCharacterService,
    PlayerCharacterService,
)
from mapBuilder.models import Room
from itemBuilder.models import Item
from itemBuilder.enum import ItemType
from grotto.game.services import ItemService, GameService


class LivingCharacterBaseView(RedirectView):
    pattern_name = "mapBuilder:play"

    def dispatch(self, request, *args, **kwargs):
        if request.character is None:
            raise Http404("Character does not exist")
        # is this character alive
        if request.character.dead:
            # send the plater back to the grotto
            self.pattern_name = "characterBuilder:crypt"
            # message about death
            messages.add_message(request, messages.INFO, request.character.deathnote)
            return super().get(request)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, dice_count=1, **kwargs):
        # get current room
        colorSlug = kwargs.get("colorSlug")
        ItemService().burnable_swap()
        game = GameService()
        if colorSlug:
            try:
                room = Room.objects.get(colorSlug=colorSlug)
            except Room.DoesNotExist:
                pass
            else:
                game.roll_to_dirty_room(room=room, dice_count=dice_count)
        service_return = game.roll_to_move_npcs(dice_count=dice_count)

        # send messages
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)

        request.character.refresh_from_db()
        if request.character.dead:
            # send the plater back to the grotto
            self.pattern_name = "characterBuilder:crypt"
            return super().get(request)
        return super().get(request, *args, **kwargs)


class EnterGrottoView(LivingCharacterBaseView):
    def get(self, request, *args, **kwargs):
        if request.character.room is None:
            # choose a random, but safe room to enter
            request.character.room = Room.objects.exclude(
                npcs__deadly=True).order_by("?")[0]
            request.character.save()
        return super().get(request, *args, **kwargs)


# class MoveView(LivingCharacterBaseView):
#     def get(self, request, *args, colorSlug, **kwargs):
#         service_return = PlayerCharacterService().move(
#             character=request.character, raises=Http404, colorSlug=colorSlug)
#         for message in service_return.messages:
#             messages.add_message(request, messages.INFO, message)
#         kwargs.update({"colorSlug": request.character.room.colorSlug, "dice_count": 1})
#         return super().get(request, *args, **kwargs)


# class FireArrowView(LivingCharacterBaseView):
#     pattern_name = "mapBuilder:room"

#     def get(self, request, *args, colorSlug, **kwargs):
#         service_return = PlayerCharacterService().fire_arrow(
#             character=request.character, colorSlug=colorSlug, raises=Http404)
#         for message in service_return.messages:
#             messages.add_message(request, messages.INFO, message)
#         kwargs.update({"colorSlug": request.character.room.colorSlug, "dice_count": 5})
#         return super().get(request, *args, **kwargs)


class BecomeCharacterView(EnterGrottoView):
    pattern_name = "mapBuilder:play"

    def dispatch(self, request, *args, character_pk, **kwargs):
        character = None
        try:
            character = Character.objects.get(user=request.user, pk=character_pk)
        except Character.DoesNotExist:
            raise Http404("Character doesn't exist")
        request.user.character = character
        request.user.save()
        request.character = character
        return super().dispatch(request, *args, **kwargs)


# class BaseItemActionView(LivingCharacterBaseView):
#     action = "test"
#     holder = "character"

#     def get(self, request, *args, item_pk, **kwargs):
#         item_service = ItemService()
#         item = item_service.get_item(
#             character=request.character, pk=item_pk, holder=self.holder, raises=Http404)
#         service_return = getattr(item_service, self.action)(
#             item=item, character=request.character)
#         for message in service_return.messages:
#             messages.add_message(request, messages.INFO, message)

#         kwargs.update({"colorSlug": request.character.room.colorSlug, "dice_count": 1})
#         return super().get(request, *args, **kwargs)


# class UseItemView(BaseItemActionView):
#     action = "use"


# class PlaceItemView(BaseItemActionView):
#     action = "place"


# class TakeItemView(BaseItemActionView):
#     action = "take"
#     holder = "room"


# class DropItemView(BaseItemActionView):
#     action = "drop"


# class ViewItemView(LivingCharacterBaseView):
#     action = "view"
#     holder = "room"
#     pattern_name = "mapBuilder:cenotaph"

#     def get(self, request, *args, item_pk, **kwargs):
#         item = ItemService().get_item(
#             character=request.character, pk=item_pk, holder=self.holder, raises=Http404)

#         kwargs.update({"colorSlug": request.character.room.colorSlug, "dice_count": 1})
#         return super().get(request, *args, **kwargs)

src/grotto/templates/static_pages/agreement.html
{% extends "base.html" %}

{% block page_title %}Code of Conduct{% endblock %}
{% block body_class %}agreement{% endblock %}
{% block main_section_class %}agreement{% endblock %}

{% block header %}<header></header>{% endblock %}

{% block content %}
updated 12/21/21
<p>
Grotto is a minimal platform for creating database-driven online game spaces. It's currently open-source and users are able create their own instances of the software. The creators of this software have applied an <a href="https://anticapitalist.software">anti-capitalist</a> software license that restricts use of this software not just to non-commercial use, but forbids uses that further the exploitation of labor towards profit.
</p>
<p>
Instances of Grotto may have norms and codes of conduct defined by the people who use them. This document that you are reading is a work in progress that defines a code of conduct for the specific instance of Grotto that is running on the wileywiggins.com domain. This instance of the Grotto software does not currently provide ways for players to interact with one another, but features are being added and changed as the underlying code is being developed for a site-specific artwork. Future versions of Grotto may contain names and life details about deceased people in the family of the software designer, as part of an artwork that utilizes the software. Future versions of the Grotto software may allow interactions that could be offensive, such as the symbolic dishonoring of deceased individuals. This is currently not a prohibited interaction. If you have questions about the specific nature of these sorts of symbolic actions, please don't hesitate to contact the email listed on the main grotto page. </p>
<p>
If features are added that allow player-to-player communication, you are expected to refrain from making unwelcome comments to other players in order to continue using the software. Some examples of these sorts of behaviors are:
<ul>
<li> Unwelcome comments regarding a person’s lifestyle choices and practices. </li>
<li> Threats, acts, or incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm. </li>
<li> Posting or threatening to post other people’s personally identifying information ("doxing"). </li>
<li> Deliberate “outing” of any aspect of a person’s identity without their consent. </li>
<li> Deliberate misgendering or use of "dead” or rejected names. </li>
<li> Gratuitous or off-topic sexual images or behavior in spaces where they’re not appropriate. </li>

<li>Unwelcome sexual attention. Physical contact and simulated physical contact through text (e.g., descriptions like “*hug*” or “*backrub*”) without consent, or after a request for no contact or to stop. </li>
<li> Deliberate intimidation. </li>
<li> Patterns of inappropriate or unwanted social contact, such as requesting or assuming inappropriate levels of intimacy with others. Continued one-on-one communication after request to cease. Stalking or unwanted following, whether in-person or online. </li>
</ul>
<p>More details about reporting and consequences for these sorts of behaviors will be added as features that present a potential for player-to-payer harassment or abuse are added. 

</p>
{% endblock %}
<a href="/index.html">Back to main page</a>

src/grotto/templates/static_pages/index.html
{% extends "base.html" %}

{% load static %}

{% block page_title %}Grotto{% endblock %}
{% block body_class %}index{% endblock %}

{% block header %}<header></header>{% endblock %}

{% block main_section_class %}welcome{% endblock %}

{% block content %}
  <h1 class="pink">Grotto (0.4<span class="small">⍺</span>)</h1>
    <img src="{% static 'images/bard.gif' %}"/ alt="an animated fantasy bard playing a stringed instrument">

    <div class="login"><a href="{% url 'characterBuilder:index' %}">ENTER</a></div>

    
    <div class="news">
      <em>The gods of forests, waters, winds and darkness vanished. Many grieved for them, and had no wish to renounce them in the waters of baptism, and in particular witches, soothsayers and magicians. They fled deeper into the forests, into secret valleys under the mountains. There they carried away with them their ancestors and their idols, and there continued to prostrate themselves before them and offer sacrifices, cursing the new God.
        - Legends of Old Bohemia
        </em>
      <p>This is an experimental web space in development! Use at your own risk. The main Grotto codebase is currently under development by <a href="https://github.com/wysiwyggins">wysiwyggins</a> and <a href="https://github.com/thismatters">Thismatters</a>. Questions? Contact Wiley Wiggins- <a href="&#109;a&#105;l&#116;&#111;:&#103;&#114;&#111;&#116;&#116;&#111;&#64;&#107;&#97;&#114;&#97;&#107;&#97;&#115;&#97;&#103;&#97;&#109;&#101;&#115;&#46;&#99;&#111;&#109;">grotto@karakasagames.com</a> </p>
      <hr/>
      Instance info:
      <ul>
        <li><a href="http://wileywiggins.com/grotto.html">About Grotto</a></li>
        <li><a href="{% url 'agreement' %}">Code of Conduct</a></li> (boilerplate, expect updates as features are added)
        <!--<li><a href="{% url 'reporting' %}">Conduct Reporting</a></li>-->
      </ul>

    </div>
{% endblock %}

src/grotto/templates/static_pages/reporting.html
{% extends "base.html" %}

{% block page_title %}Conduct Reporting{% endblock %}
{% block body_class %}reporting{% endblock %}
{% block main_section_class %}reporting{% endblock %}

{% block header %}<header></header>{% endblock %}

{% block content %}
  <p>This Grotto has not yet configured a reporting form. </p>
{% endblock %}