src/characterBuilder/urls.py
from django.urls import path

from . import views

app_name = "characterBuilder"
urlpatterns = [
    # ex: /polls/
    path("", views.Index.as_view(), name="index"),
    path("character/<int:pk>/", views.CharacterDetailView.as_view(), name="character"),
    path("test/", views.CharacterTestView.as_view(), name="character-test"),
    path(
        "write-test/",
        views.CharacterTestCreateView.as_view(),
        name="character-test-create",
    ),
    path("new-character/", views.NewCharacterView.as_view(), name="new-character"),
    path("crypt/", views.CryptView.as_view(), name="crypt"),
]

src/grotto/game/urls.py
from django.urls import path

from . import views

app_name = "game"
urlpatterns = [
    path("enter/", views.EnterGrottoView.as_view(), name="enter"),
    # path("move/<slug:colorSlug>/", views.MoveView.as_view(), name="move"),
    # path("fire/<slug:colorSlug>/", views.FireArrowView.as_view(), name="fire"),
    path("become/<int:character_pk>/", views.BecomeCharacterView.as_view(), name="become"),
    # path("itemActions/use/<int:item_pk>/", views.UseItemView.as_view(), name="use"),
    # path("itemActions/take/<int:item_pk>/", views.TakeItemView.as_view(), name="take"),
    # path("itemActions/place/<int:item_pk>/", views.PlaceItemView.as_view(), name="place"),
    # path("itemActions/drop/<int:item_pk>/", views.DropItemView.as_view(), name="drop"),
    # path("itemActions/view/<int:item_pk>/", views.ViewItemView.as_view(), name="view"),
]

src/grotto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from grotto.views import RegisterView, TermsAcceptView

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("rooms/", include("mapBuilder.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", RegisterView.as_view(), name="register"),
    path("guild/", include("characterBuilder.urls")),
    path("game/", include("grotto.game.urls")),
    path("api/v1/", include("grotto.api.urls")),
    path("terms/", TermsAcceptView.as_view(), name="terms"),
    path(
        "privacy/",
        TemplateView.as_view(template_name="static_pages/privacy.html"),
        name="privacy",
    ),
    path(
        "agreement/",
        TemplateView.as_view(template_name="static_pages/agreement.html"),
        name="agreement",
    ),
    path(
        "reporting/",
        TemplateView.as_view(template_name="static_pages/reporting.html"),
        name="reporting",
    ),
]

src/characterBuilder/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

from mapBuilder.models import Room
from itemBuilder.enum import ItemType


class User(AbstractUser):
    """Placeholder User model in case we need to add fields in the future
    https://docs.djangoproject.com/en/3.1/topics/auth/customizing/...
      #using-a-custom-user-model-when-starting-a-project
    """

    accepts_terms = models.BooleanField(default=False)
    character = models.OneToOneField("Character", blank=True, null=True, on_delete=models.SET_NULL, related_name="chosen_one")


class NamedModel(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Character(NamedModel):
    kind = models.CharField(max_length=200)
    description = models.TextField()
    pub_date = models.DateTimeField("date created", default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="characters")
    room = models.ForeignKey(
        Room, on_delete=models.SET_NULL, null=True, blank=True, related_name="occupants"
    )
    # arrow_count = models.IntegerField(default=1)
    dead = models.BooleanField(default=False)
    deathnote = models.CharField(max_length=200, null=True, blank=True)
    # items = models.ManyToManyField("Item", blank=True)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    @property
    def arrow_count(self):
        return self.inventory.filter(abstract_item__itemType=ItemType.ARROW).count()


class NonPlayerCharacter(NamedModel):
    room = models.ForeignKey(Room, on_delete=models.PROTECT, related_name="npcs", null=True, blank=True)
    mobile = models.BooleanField(default=True)
    deadly = models.BooleanField(default=True)
    mortal = models.BooleanField(default=True)
    demonic = models.BooleanField(default=False)
    movement_entropy = models.IntegerField(
        default=0, help_text="See Movement Threshold"
    )
    movement_threshold = models.IntegerField(
        default=100,
        help_text="When Movement Entropy exceeds this threshold the NPC will move",
    )
    warning_text = models.CharField(max_length=200)
    greeting = models.CharField(max_length=140, null=True, blank=True)


class Skill(NamedModel):
    level = models.IntegerField()
    character = models.ForeignKey(
        Character, on_delete=models.CASCADE, related_name="skills"
    )


# class Item(NamedModel):
#     # permissions = ...
#     # Eventually items could imbue the carrier with some special powers which
#     #   can be faciliated using django permissions.
#     persistent = models.BooleanField(default=True)


class CharacterTest(models.Model):
    question = models.CharField(max_length=2000)


class CharacterTestChoice(models.Model):
    character_test = models.ForeignKey(
        CharacterTest, on_delete=models.CASCADE, related_name="choices"
    )
    choice = models.CharField(max_length=400)


class Visit(models.Model):
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True, related_name="_visits")
    character = models.ForeignKey(Character, on_delete=models.SET_NULL, null=True)
    stamp_date = models.DateTimeField("date created", default=timezone.now)
    died_here = models.BooleanField(default=False)

src/characterBuilder/views.py
from random import choice, randint

from django import forms
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.generic import FormView, RedirectView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from rest_framework.authtoken.models import Token

from grotto.views import ActionMixin, LoginRequiredMixin
from grotto.game.services import CharacterCreationService

from .models import Character, CharacterTest, CharacterTestChoice

# Create your views here.


class Index(LoginRequiredMixin, ActionMixin, ListView):
    template_name = "guild.html"
    model = Character
    paginate_by = 25
    actions = [
        {
            "text": "Speak to Crone (Create Character)",
            "url": "/guild/test/",
        },

        {
            "text": "Visit the Crypt",
            "url": "/guild/crypt/",
        }
    ]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user, dead=False)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        context["token"] = Token.objects.get_or_create(user=self.request.user)[0]
        return context


class CharacterDetailView(ActionMixin, DetailView):
    model = Character
    template_name = "character.html"
    query_pk_and_slug = True
    actions = [
        {
            "text": "Go to Guild Hall",
            "url": "/guild/",
        },
        {
            "text": "Enter the grotto",
            "url": "/game/become/{character_pk}/",
            "become": True,
        },
        {
            "text": "Roll New Character",
            "url": "/guild/test/",
        },
    ]

    def formatted_actions(self):
        _formatted = []
        if self.request.user.is_anonymous:
            return [{
                "text": "Log in",
                "url": "/accounts/login/"
            }]

        if not self.is_players_character:
            # just provide link back to grotto
            return [{
                "text": "Continue",
                "url": "/game/enter/"
            }]
        for action in self.actions:
            if action.get("become", False) and not self.is_players_character:
                # Don't put a link to enter the grotto unless this is your character
                continue
            _formatted.append({
                "text": action["text"],
                "url": action["url"].format(character_pk=self.character_pk),
            })
        return _formatted

    def get(self, request, *args, **kwargs):
        self.character_pk = kwargs["pk"]
        self.is_players_character = False
        if not request.user.is_anonymous:
            self.is_players_character = Character.objects.filter(user=request.user, id=kwargs["pk"]).exists()
        return super().get(request, *args, **kwargs)


class CharacterTestView(LoginRequiredMixin, ActionMixin, TemplateView):
    template_name = "character_test.html"
    actions = [
        {
            "url": "/guild/test/",
            "text": "Take a different test",
        },
        {
            "url": "/guild/write-test/",
            "text": "Create a test",
        },
    ]
    alt_actions = [{"text": "View Character", "url": "/guild/new-character/"}]

    def get_context_data(self, satisfied=False, another=False, **kwargs):
        asked = []
        _asked = self.request.session.get("questions_asked")
        if _asked:
            asked = [int(q) for q in _asked.split(",")]
        pks = CharacterTest.objects.exclude(id__in=asked).values_list("id", flat=True).order_by("id")
        ctx = {}
        if not pks or satisfied:
            self.actions = self.alt_actions
            self.request.session["questions_asked"] = None
        else:
            random_pk = choice(pks)
            character_test = CharacterTest.objects.get(id=random_pk)
            ctx.update(
                {
                    "question": character_test.question,
                    "answer_choices": character_test.choices.all(),
                    "another": another,
                }
            )
            asked.append(random_pk)
            self.request.session["questions_asked"] = ",".join([str(q) for q in asked])

        context = super().get_context_data(**kwargs)
        context.update(ctx)
        return context

    def post(self, request, *args, **kwargs):
        # possibly validate that form a little bit
        # roll a D20
        roll = randint(1, 20)
        if roll > 12:
            # enough questions answered
            context = self.get_context_data(satisfied=True)
            return self.render_to_response(context)
        # otherwise ask another question
        context = self.get_context_data(another=True)
        return self.render_to_response(context)


class NewCharacterView(LoginRequiredMixin, RedirectView):
    pattern_name = "characterBuilder:character"

    def get(self, request, *args, **kwargs):
        # actually create the character and associate to user
        character = CharacterCreationService().create(user=request.user)
        kwargs.update({"pk": character.pk})
        return super().get(request, *args, **kwargs)


class CharacterTestCreateView(LoginRequiredMixin, ActionMixin, TemplateView):
    template_name = "character_test_create.html"

    def post(self, request, *args, **kwargs):
        errors = []
        context = self.get_context_data()
        question = request.POST.get("question", "").strip()
        if not question:
            errors.append("you must ask a question")
        answers = [a for a in request.POST.getlist("answer") if a.strip()]
        if len(answers) < 2:
            errors.append("you must provide at least two answers")
        if errors:
            context.update({"errors": errors})
            return self.render_to_response(context)
        # create the model instances
        test = CharacterTest.objects.create(question=question)
        for answer in answers:
            CharacterTestChoice.objects.create(character_test=test, choice=answer)
        return redirect("/guild/test/")


class CryptView(LoginRequiredMixin, ActionMixin, ListView):
    template_name = "crypt.html"
    model = Character
    actions = [{
            "url": "/guild/",
            "text": "Return to guild hall",
        }]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(dead=True)
        return queryset

src/characterBuilder/templates/character.html
{% extends "base.html" %}

{% block page_title %}
  {{ object.name }}
{% endblock %}

{% block body_class %}
  character {{ object.name }}
{% endblock %}

{% block content %}
  <div class="character_sheet">
    <h2>{{object.name}} the {% if object.dead %}dead {% endif %}{{object.kind}}</h2>
    <p>Name: {{object.name}}</p>
    <p>Kind: {{object.kind}}</p>
    <p class="description">
      Description: {{ object.description }}
    </p>
    <p class="skills">
      <h3>Skills:</h3>
      <ul>
        {% for skill in object.skills.all %}
          <li>{{ skill.name }}: {{ skill.level }}</li>
          {% empty %}
          (None)
          {% endfor %}
      </ul>
    </p>
    <p class="inventory">
      <h3>Inventory:</h3>
    <ul>
      {# deal with other items too #}

      {% for item in character.inventory.all %}
        <li>{{ item.name }}</li>
      {% endfor %}
    </ul>
    </p>
  </div>
{% endblock %}

{% block page_script %}

{% endblock %}

src/characterBuilder/templates/character_test.html
{% extends "base.html" %}

{% block content %}
  <div class="poll">
    {% if question %}
      {% if another %}
      <p><em>Unsatisfied, the crone demands you answer another question...</em></p>
      {% endif %}
      <p><em>The crone penetrates you with her all-seeing eye and asks...</em></p>

      <form method="post">
        {% csrf_token %}
        {{ question }}
        <br />
        <br />
        {% for choice in answer_choices %}
          <input id="choice-{{ choice.pk}}" type="radio" name="choice" value="{{ choice.pk }}"><label for="choice-{{ choice.pk}}">{{ choice.choice }}</label><br />
        {% endfor %}

        <button type="submit" name="generate_character">Submit Answer</button>
      </form>
    {% else %}
      <p>The Crone says:</p>
      <p>You have answered my questions and I can see clearly what sort of a being you are. Now... know thyself!</p>
    {% endif %}
  </div>
{% endblock %}

src/characterBuilder/templates/character_test_create.html
{% extends "base.html" %}

{% block content %}
  {% if errors %}
    <ul>
      {% for error in errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <input type="text" name="question" id="question" /><label for="question">What is your question?</label><br />
    <input type="text" name="answer" id="answer-1" /><label for="answer-1">Answer choice</label><br />
    <input type="text" name="answer" id="answer-2" /><label for="answer-2">Answer choice</label><br />
    <input type="text" name="answer" id="answer-3" /><label for="answer-3">Answer choice</label><br />
    <input type="text" name="answer" id="answer-4" /><label for="answer-4">Answer choice</label><br />
    <input type="text" name="answer" id="answer-5" /><label for="answer-5">Answer choice</label><br />
    <input type="text" name="answer" id="answer-6" /><label for="answer-6">Answer choice</label><br />
    <input type="text" name="answer" id="answer-7" /><label for="answer-7">Answer choice</label><br />
    <input type="text" name="answer" id="answer-8" /><label for="answer-8">Answer choice</label><br />
    <button type="submit" name="create_test">Create Test</button>
  </form>

{% endblock %}

src/characterBuilder/templates/crypt.html
{% extends "base.html" %}

{% block content %}
  <h2>The Crypt</h2>
  <p>A musty stone chamber in whose chiseled coffers rest the brittle remains of the moribund.</p>

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <ul>
    {% for character in object_list %} 
        <li><a href="{% url 'characterBuilder:character' character.pk %}">{{ character.name }}</a> (created {{ character.pub_date|date }})</li>
    {% empty %}
        <li>nobody.</li>
    {% endfor %}
  </ul>
{% endblock %}

src/characterBuilder/templates/guild.html
{% extends "base.html" %}

{% block content %}
  <h2>The Adventurer's Guild</h2>
  <p>This is the waiting area outside of the maze. Seated at a table in a darkened corner is a smiling crone. She gestures towards an empty seat and shuffles a tarot deck.</p>
  <p>The barkeep has slipped a note into your pocket containing a cryptic message, it must have some secret meaning. It says: "<span class="secret authentication-header">Token {{ token.key }}</span>"</p>
  <p>"To switch between text and GUI views use the <kbd>`</kbd> key," he says incomprehensibly.</p>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <p>
    Squinting at a glint of light in the crone's crystal ball you see:
  </p>
  <ul>
    {% for character in object_list %}
        <li><a href="{% url 'characterBuilder:character' character.pk %}">{{ character.name }}</a> &mdash; <a href="{% url 'game:become' character.pk %}">become</a> (created {{ character.pub_date|date }})</li>
    {% empty %}
        <li>nobody.</li>
    {% endfor %}
  </ul>
  <!-- <a href="{% url 'characterBuilder:character-test' %}">Create Character</a> -->
{% endblock %}