src/grotto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from grotto.views import RegisterView, TermsAcceptView

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("rooms/", include("mapBuilder.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", RegisterView.as_view(), name="register"),
    path("guild/", include("characterBuilder.urls")),
    path("game/", include("grotto.game.urls")),
    path("api/v1/", include("grotto.api.urls")),
    path("terms/", TermsAcceptView.as_view(), name="terms"),
    path(
        "privacy/",
        TemplateView.as_view(template_name="static_pages/privacy.html"),
        name="privacy",
    ),
    path(
        "agreement/",
        TemplateView.as_view(template_name="static_pages/agreement.html"),
        name="agreement",
    ),
    path(
        "reporting/",
        TemplateView.as_view(template_name="static_pages/reporting.html"),
        name="reporting",
    ),
]

src/mapBuilder/api/urls.py
from django.urls import path
from rest_framework import routers

from mapBuilder.api import views

app_name = "map-api"

urlpatterns = [
    # path("room/<int:pk>/", views.RoomView.as_view(), name="room")
]

src/mapBuilder/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mapBuilder.views import Index

from . import views

app_name = "mapBuilder"
urlpatterns = [
    # ex: /polls/
    path("", views.Index.as_view(), name="index"),
    path("play/", views.PlayDetailView.as_view(), name="play"),
    path("<slug:colorSlug>/", views.RoomDetailView.as_view(), name="room"),
    path("cenotaph/<slug:colorSlug>/", views.CenotaphView.as_view(), name="cenotaph"),
]

src/mapBuilder/models.py
import os
from datetime import timedelta

from colorfield.fields import ColorField
from django.db import models
from django.utils.timezone import now

from itemBuilder.enum import ItemType
from mapBuilder.validators import validate_pdf_image_or_audio


class Room(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField(max_length=200, blank=True)
    exits = models.ManyToManyField("self", symmetrical=True)
    pub_date = models.DateTimeField(default=now, blank=True)
    description = models.TextField()
    colorName = models.CharField(max_length=200)
    status = models.CharField(max_length=200, blank=True)
    colorHex = ColorField(default="#222222")
    colorSlug = models.SlugField(null=True)
    # video embeds
    hosted_video_link = models.URLField(max_length=200, blank=True)
    vimeo_id = models.CharField(max_length=200, blank=True)
    youtube_id = models.CharField(max_length=200, blank=True)
    cleanliness = models.IntegerField(default=1)
    is_cursed = models.BooleanField(default=False)

    class Meta:
        unique_together = ["id", "url"]

    def __str__(self):
        return self.name

    def _room_level(self, *, item_type):
        # check items in room
        _item = self.items.filter(abstract_item__itemType=item_type, active__isnull=False)

        active_item_count = sum([1 for candle in _item if candle.is_active])
        # active_item_count = 1
        if active_item_count > 0:
            return 2
        # check characters in self
        for character in self.occupants.all():
            # see if character has a candle
            _item = character.inventory.filter(abstract_item__itemType=item_type, active__isnull=False)
            active_item_count = sum([1 for candle in _item if candle.is_active])
            if active_item_count > 0:
                return 1
        return 0

    def get_attributes(self):
        sanctity = 0
        if not self.is_cursed:
            sanctity = self._room_level(item_type=ItemType.INCENSE)
        return {
            "cleanliness": self.cleanliness,
            "brightness": self._room_level(item_type=ItemType.CANDLE),
            "sanctity": sanctity,
        }

    def warnings(self):
        _warnings = []
        for exit in self.exits.all().prefetch_related("npcs").order_by("?"):
            _warnings.extend(exit.npcs.all().values_list("warning_text", flat=True))
        # ensure that the warnings are in a random order so that the
        return _warnings

    @property
    def visible_items(self):
        if self._room_level(item_type=ItemType.CANDLE) == 0:
            return self.items.all().none()
        return self.items.all()

    @property
    def visits(self):
        deduped_visits = []
        visitors = []
        visits = (
            self._visits.all().filter(room=self)
            .exclude(stamp_date__lt=now() - timedelta(days=7))
            .order_by("-stamp_date")
        )
        for visit in visits:
            if visit.character not in visitors:
                deduped_visits.append(visit)
                visitors.append(visit.character)
        return deduped_visits


def centaph_portrait_uploads(instance, filename):
    name = f"cenotaph/portraits/{filename}"
    return name


class Cenotaph(models.Model):
    room = models.OneToOneField(Room, on_delete=models.PROTECT, related_name="cenotaph")
    text = models.TextField(help_text="The inscription on the cenotaph")
    name = models.CharField(max_length=64)
    birth = models.CharField(max_length=32, null=True, blank=True)
    death = models.CharField(max_length=32, null=True, blank=True)
    scene = models.TextField(help_text="This 'a-frame' will be inserted in the cenotaph as background", null=True, blank=True)
    portrait_filename = models.CharField(max_length=128, null=True, blank=True)
    portrait = models.FileField(
        upload_to=centaph_portrait_uploads,
        validators=[validate_pdf_image_or_audio],
        null=True,
    )


class RoomEvent(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="events")
    created = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=256)


def centaph_file_uploads(instance, filename):
    ext = os.path.splitext(filename)[1]
    name = f"cenotaph/{instance.cenotaph.pk}_{now()}{ext}"
    print(name)
    return name


class CenotaphFile(models.Model):
    cenotaph = models.ForeignKey(
        Cenotaph, on_delete=models.CASCADE, related_name="files")
    file = models.FileField(
        upload_to=centaph_file_uploads,
        validators=[validate_pdf_image_or_audio],
    )
    original_filename = models.CharField(max_length=128, blank=True)
    extension = models.CharField(max_length=8, blank=True)

    def __str__(self):
        return f"{self.original_filename}{self.extension}"

    def save(self, **kwargs):
        """If this is the first time saving, then capture the original
        filename"""
        if not self.id:
            self.original_filename, self.extension = os.path.splitext(str(self.file))
        return super().save(**kwargs)

src/mapBuilder/api/views.py
from rest_framework import generics

from mapBuilder import models
from mapBuilder.api import serializers

class RoomView(generics.RetrieveAPIView):
    lookup_url_kwarg = "pk"
    queryset = models.Room.objects.all()
    serializer_class = serializers.RoomSerializer

src/mapBuilder/views.py
from random import sample
from datetime import timedelta

from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from characterBuilder.models import Character, Visit
from grotto.views import ActionMixin, LoginRequiredMixin
from grotto.game.services import RoomService
from mapBuilder.models import Room
from itemBuilder.enum import ItemType


class Index(LoginRequiredMixin, ListView):
    template_name = "mapBuilder/index.html"
    model = Room
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        return context

    def post(self, request):
        RoomService().generate()
        return redirect(".")  # points the user right back where they came from


class PlayDetailView(LoginRequiredMixin, TemplateView):
    template_name = "mapBuilder/play.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "room_context": {
                    "user": {
                        "is_anonymous": self.request.user.is_anonymous,
                        "is_staff": self.request.user.is_staff,
                    },
                    "base_url": settings.BASE_URL,
                }
            }
        )
        return context


class RoomDetailView(DetailView):
    model = Room
    template_name = "mapBuilder/room.html"
    query_pk_and_slug = True
    slug_url_kwarg = "colorSlug"
    slug_field = "colorSlug"
    sanctity_adjectives = ("Cursed", "Mundane", "Sacred")
    cleanliness_adjectives = ("Profane", "Dirty", "Clean")
    actions = []

    def _room_level(self, item_type):
        room = self.object
        # check items in room
        _item = room.items.filter(
            abstract_item__itemType=item_type, active__isnull=False
        )

        active_item_count = sum([1 for candle in _item if candle.is_active])
        # active_item_count = 1
        if active_item_count > 0:
            return 2
        # check characters in room
        for character in room.occupants.all():
            # see if character has a candle
            _item = character.inventory.filter(
                abstract_item__itemType=item_type, active__isnull=False
            )
            active_item_count = sum([1 for candle in _item if candle.is_active])
            if active_item_count > 0:
                return 1
        return 0

    def get_room_level(self, descriptor="illumination"):
        room = self.object
        if descriptor == "cleanliness":
            return room.cleanliness
        if descriptor == "illumination":
            return self._room_level(ItemType.CANDLE)
        if descriptor == "sanctity":
            if room.is_cursed:
                return 0
            if self._room_level(ItemType.INCENSE) == 2:
                return 2
            return 1

    def get_room_adjective(self, descriptor):
        _level = self.get_room_level(descriptor)
        adjectives = getattr(self, f"{descriptor}_adjectives")
        try:
            return adjectives[_level]
        except IndexError:
            return "what?"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "visits": self.object.visits,
                "illumination_level": self.get_room_level("illumination"),
                "sanctity_adjective": self.get_room_adjective("sanctity"),
                "cleanliness_adjective": self.get_room_adjective("cleanliness"),
            }
        )
        return context

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class CenotaphView(DetailView):
    model = Room
    template_name = "mapBuilder/room.html"
    query_pk_and_slug = True
    slug_url_kwarg = "colorSlug"
    slug_field = "colorSlug"
    template_name = "mapBuilder/cenotaph.html"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        try:
            return obj.cenotaph
        except ObjectDoesNotExist:
            raise Http404("No cenotaph here")

src/templates/mapBuilder/cenotaph.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block page_title %}{{object.name}}{% endblock %}

{% block body_class %}cenotaph{% endblock %}

{% block body_style %}background-color:{{object.room.colorHex}}{% endblock %}

{% block inner_body %}
  <div class="content">
    <div class="main">
      <div class="foreground">
        <header>
          <h1>{{object.name}}</h1>
          {% if object.birth %}{{ object.birth }}{% else %}????{% endif%}&mdash;{% if object.death %}{{ object.death }}{% else %}????{% endif%}
        </header>

        <img id="portrait" class="portrait" src="{{ object.portrait.url }}"/>

        <div class="obituary">
            <h3>Inscription:</h3>
            {{object.text|safe}}
        </div>
        <h3>Cenotaph Manifest:</h3>
        <ul class="events">
          {% for event in object.room.events.all reversed %}
            <li>{{ event.text }} &mdash; {{ event.created | naturaltime }}</li>
          {% endfor %}
        </ul>

      </div>
      {{object.scene|safe}}
    </div>
    
    <div class="characterPanel">
      <div class="status-bar">
        You examine the Cenotaph
      </div>
      <div class="action-bar">
        {% if request.user.is_anonymous %}
          <a href="{% url 'mapBuilder:room' object.room.colorSlug %}">Return</a>
        {% else %}
          <a href="{% url 'mapBuilder:play' %}">Return</a>
        {% endif %}
      </div>
    </div>
  </div>
  
{% endblock %}

src/templates/mapBuilder/index.html
{% extends "base.html" %}

{% block content %}
    <h2>The map of <span class="yellow">Grotto</span> as we know it:</h2>
    <p>Spread out on the bed is a map and the tumped-out contents of a junk drawer.</p>

        <ul class="exits">
          {% for room in object_list %}
              <li><a href="{% url 'mapBuilder:room' room.colorSlug %}">{{ room.name }}</a> (created {{ room.pub_date|date }})</li>
          {% empty %}
              <li>No rooms yet.</li>
          {% endfor %}
          </ul>

        <form method="post">
          {% csrf_token %}
          <button type="submit" name="generate_room">Add Room to Map</button>
        </form>
{% endblock %}

src/templates/mapBuilder/new_room.html
{% extends "base.html" %}
{% load django_svelte %}

{% block page_title %}Loading...{% endblock %}

{% block inner_body %}
    {% display_svelte "Room.svelte" room_context %}
{% endblock %}

src/templates/mapBuilder/play.html
{% extends "base.html" %}
{% load django_svelte %}

{% block page_title %}Loading...{% endblock %}

{% block inner_body %}
    {% display_svelte "Room.svelte" room_context %}
{% endblock %}

{% block toggle_view_script %}
{% endblock %}

src/templates/mapBuilder/room.html
{% extends "base.html" %}

{% load humanize %}

{% block page_title %}{{object.name}}{% endblock %}

{% block body_class %}room {{ object.colorName }} illuminate-{{illumination_level}} {% endblock %}

{% block body_style %}background-color:{{object.colorHex}}{% endblock %}

{% block sidebar %}
  <sidebar>
    <h2>Exits:</h2>
    <ul class="exits">
      {% for exit in object.exits.all %}
        <li><a href="{% url 'mapBuilder:room' exit.colorSlug %}">{{exit.name}}</a></li>
      {% endfor %}
    </ul>
  </sidebar>
{% endblock %}

{% block content %}
  <h2>{{object.name}}</h2>
  <p>The room is {{ sanctity_adjective }} and {{ cleanliness_adjective }}. {% if illumination_level == 1 %}A player is holding a candle which dimly lights the room. A candle-holder on the wall is empty.{% elif illumination_level == 2%}A burning candle lights the room.{% else %}The room is totally dark.{% endif %}</p>
  <p class="description">{{ object.description }}</p>
  {% if object.cenotaph %}
  <p class="cenotaph"><a href="{% url 'mapBuilder:cenotaph' object.colorSlug %}">View Cenotaph</a></p>
  {% endif %}
  {% comment %}
  log of events which occurred in this room
  {% endcomment %}
  <ul class="events">
    {% for event in object.events.all reversed %}
      <li>{{ event.text }} &mdash; {{ event.created | naturaltime }}</li>
    {% endfor %}
  </ul>
  <ul class="visits">
    {% for visit in visits %}
      {% if visit.character == character %}
        <li>You were here {{ visit.stamp_date | naturaltime }}</li>
      {% elif not visit.character %}
        <li>Something strange was here {{ visit.stamp_date | naturaltime }}</li>
      {% else %}
        <li>An unknown {{ visit.character.kind | lower }} was here {{ visit.stamp_date | naturaltime }}</li>
      {% endif %}
    {% endfor %}
  </ul>
{% endblock %}